name: Build rules dat files
on:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *" # 1:00 GMT+7
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "GOAMD64=v3" >> $GITHUB_ENV
          echo "BUILDTIME=$(TZ=Asia/Jakarta date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
          echo "GOOGLE_DOMAINS_URL=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf" >> $GITHUB_ENV
          echo "APPLE_DOMAINS_URL=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf" >> $GITHUB_ENV
          echo "EASYLISTCHINA_EASYLIST_REJECT_URL=https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt" >> $GITHUB_ENV
          echo "PETERLOWE_REJECT_URL=https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext" >> $GITHUB_ENV
          echo "ADGUARD_DNS_REJECT_URL=https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt" >> $GITHUB_ENV
          echo "DANPOLLOCK_REJECT_URL=https://someonewhocares.org/hosts/hosts" >> $GITHUB_ENV
          echo "RULE_ADS_ULTIMATE=https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/hosts/ultimate.txt" >> $GITHUB_ENV
          echo "WIN_SPY=https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt" >> $GITHUB_ENV
          echo "WIN_UPDATE=https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/update.txt" >> $GITHUB_ENV
          echo "WIN_EXTRA=https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/extra.txt" >> $GITHUB_ENV
          echo "OISD_FULL=https://big.oisd.nl/dnsmasq" >> $GITHUB_ENV
          echo "OISD_SMALL=https://small.oisd.nl/dnsmasq" >> $GITHUB_ENV
          echo "OISD_NSFW=https://nsfw.oisd.nl/dnsmasq" >> $GITHUB_ENV
          echo "DOH_DNS=https://raw.githubusercontent.com/dibdot/DoH-IP-blocklists/master/doh-domains.txt" >> $GITHUB_ENV
          echo "RULE_ADS=https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt" >> $GITHUB_ENV
          echo "RULE_ADS_EXTENDED=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/rule_ads.txt" >> $GITHUB_ENV
          echo "RULE_GAME=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/rule_gaming.txt" >> $GITHUB_ENV
          echo "RULE_INDO=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/rule_indo.txt" >> $GITHUB_ENV
          echo "RULE_PS=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/rule_playstore.txt" >> $GITHUB_ENV
          echo "RULE_SOSMED=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/rule_sosmed.txt" >> $GITHUB_ENV
          echo "RULE_STREAMING=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/rule_streaming.txt" >> $GITHUB_ENV
          echo "RULE_UMUM=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/rule_umum.txt" >> $GITHUB_ENV
          echo "RULE_IPCHECK=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/rule_ipcheck.txt" >> $GITHUB_ENV
          echo "RULE_VIDCONFERENCE=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/rule-videoconference.txt" >> $GITHUB_ENV
          echo "URLTEST=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/urltest.txt" >> $GITHUB_ENV
          echo "RULE_SPEEDTEST=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/rule_speedtest.txt" >> $GITHUB_ENV
          echo "MALICIOUS_HOST=https://raw.githubusercontent.com/elliotwutingfeng/Inversion-DNSBL-Blocklists/main/Google_hostnames_light.txt" >> $GITHUB_ENV
          echo "RULE_BANK_ID=https://raw.githubusercontent.com/rizkikotet-dev/GeoSite-WRT/rule/rule_bank-id.txt" >> $GITHUB_ENV
        shell: bash

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: rtaserver/meta-rules-dat

      - name: Checkout Loyalsoldier/domain-list-custom
        uses: actions/checkout@v3
        with:
          repository: Loyalsoldier/domain-list-custom
          path: custom

      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v3
        with:
          repository: v2fly/domain-list-community
          path: community

      - name: Checkout cokebar/gfwlist2dnsmasq
        uses: actions/checkout@v3
        with:
          repository: cokebar/gfwlist2dnsmasq
          path: gfwlist2dnsmasq

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: ./custom/go.sum

      - name: Get geoip.dat relative files
        run: |
          wget https://github.com/Loyalsoldier/geoip/raw/release/geoip.dat
          wget https://github.com/Loyalsoldier/geoip/raw/release/geoip.dat.sha256sum

      - name: Generate GFWList domains
        run: |
          cd gfwlist2dnsmasq || exit 1
          chmod +x ./gfwlist2dnsmasq.sh
          ./gfwlist2dnsmasq.sh -l -o ./temp-gfwlist.txt

      - name: Get and add proxy domains into temp-proxy.txt file
        run: |
          cat ./gfwlist2dnsmasq/temp-gfwlist.txt | perl -ne '/^((?=^.{3,255})[a-zA-Z0-9][-_a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-_a-zA-Z0-9]{0,62})+)/ && print "$1\n"' > temp-proxy.txt
          curl -sSL $GOOGLE_DOMAINS_URL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' >> temp-proxy.txt
          curl -sSL $APPLE_DOMAINS_URL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' >> temp-proxy.txt

      - name: Get and add reject domains into temp-reject.txt file
        run: |
          curl -sSL $EASYLISTCHINA_EASYLIST_REJECT_URL | perl -ne '/^\|\|([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})\^$/ && print "$1\n"' | perl -ne 'print if not /^[0-9]{1,3}(\.[0-9]{1,3}){3}$/' > temp-reject.txt
          curl -sSL $ADGUARD_DNS_REJECT_URL | perl -ne '/^\|\|([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})\^$/ && print "$1\n"' | perl -ne 'print if not /^[0-9]{1,3}(\.[0-9]{1,3}){3}$/' >> temp-reject.txt
          curl -sSL $PETERLOWE_REJECT_URL | perl -ne '/^127\.0\.0\.1\s([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})$/ && print "$1\n"' >> temp-reject.txt
          curl -sSL $DANPOLLOCK_REJECT_URL | perl -ne '/^127\.0\.0\.1\s([-_0-9a-zA-Z]+(\.[-_0-9a-zA-Z]+){1,64})/ && print "$1\n"' | sed '1d' >> temp-reject.txt
          
      - name: Add proxy, direct and reject domains from "hidden" branch to appropriate temp files
        run: |
          cat ./resouces/proxy.txt >> temp-proxy.txt
          cat ./resouces/direct.txt >> temp-direct.txt
          cat ./resouces/reject.txt >> temp-reject.txt

      - name: Sort and generate redundant lists
        run: |
          cat temp-proxy.txt | sort --ignore-case -u > proxy-list-with-redundant
          cat temp-direct.txt | sort --ignore-case -u > direct-list-with-redundant
          cat temp-reject.txt | sort --ignore-case -u > reject-list-with-redundant

      - name: Remove redundant domains
        run: |
          chmod +x ./resouces/*.py
          python ./resouces/findRedundantDomain.py ./direct-list-with-redundant ./direct-list-deleted-unsort
          python ./resouces/findRedundantDomain.py ./proxy-list-with-redundant ./proxy-list-deleted-unsort
          python ./resouces/findRedundantDomain.py ./reject-list-with-redundant ./reject-list-deleted-unsort
          [ ! -f "direct-list-deleted-unsort" ] && touch direct-list-deleted-unsort
          [ ! -f "proxy-list-deleted-unsort" ] && touch proxy-list-deleted-unsort
          [ ! -f "reject-list-deleted-unsort" ] && touch reject-list-deleted-unsort
          sort ./direct-list-deleted-unsort > ./direct-list-deleted-sort
          sort ./proxy-list-deleted-unsort > ./proxy-list-deleted-sort
          sort ./reject-list-deleted-unsort > ./reject-list-deleted-sort
          python ./resouces/removeFrom.py -remove ./direct-list-deleted-sort -from ./direct-list-with-redundant -out direct-list-without-redundant
          python ./resouces/removeFrom.py -remove ./proxy-list-deleted-sort -from ./proxy-list-with-redundant -out proxy-list-without-redundant
          python ./resouces/removeFrom.py -remove ./reject-list-with-redundant -from ./reject-list-with-redundant -out reject-list-without-redundant

      - name: Create `Geosites List`
        run: |
          cat ./gfwlist2dnsmasq/temp-gfwlist.txt | perl -ne '/^((?=^.{3,255})[a-zA-Z0-9][-_a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-_a-zA-Z0-9]{0,62})+)/ && print "$1\n"' >> ./community/data/gfw
          curl -sSL $WIN_SPY | grep "0.0.0.0" | awk '{print $2}' > ./community/data/win-spy
          curl -sSL $WIN_UPDATE | grep "0.0.0.0" | awk '{print $2}' > ./community/data/win-update
          curl -sSL $WIN_EXTRA | grep "0.0.0.0" | awk '{print $2}' > ./community/data/win-extra
          curl -sSL $RULE_ADS_ULTIMATE | grep "0.0.0.0" | awk '{print $2}' > ./community/data/ads-ultimate
          curl -sSL $OISD_FULL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./community/data/oisd-full
          curl -sSL $OISD_FULL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > oisd-full.txt
          curl -sSL $OISD_SMALL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./community/data/oisd-small
          curl -sSL $OISD_SMALL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > oisd-small.txt
          curl -sSL $RULE_ADS | grep "0.0.0.0" | awk '{print $2}' > ./community/data/rule-ads
          curl -sSL $RULE_ADS_EXTENDED >> ./community/data/rule-ads
          curl -sSL $RULE_ADS | grep "0.0.0.0" | awk '{print $2}' > rule-ads.txt
          curl -sSL $RULE_ADS_EXTENDED >> rule-ads.txt
          curl -sSL $OISD_NSFW | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./community/data/oisd-nsfw
          curl -sSL $OISD_NSFW | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > oisd-nsfw.txt
          wget -O ./community/data/rule-doh $DOH_DNS
          wget -O rule-doh.txt $DOH_DNS
          wget -O ./community/data/rule-gaming $RULE_GAME
          wget -O rule-gaming.txt $RULE_GAME
          wget -O ./community/data/rule-indo $RULE_INDO
          wget -O rule-indo.txt $RULE_INDO
          wget -O ./community/data/rule-playstore $RULE_PS
          wget -O rule-playstore.txt $RULE_PS
          wget -O ./community/data/rule-sosmed $RULE_SOSMED
          wget -O rule-sosmed.txt $RULE_SOSMED
          wget -O ./community/data/rule-streaming $RULE_STREAMING
          wget -O rule-streaming.txt $RULE_STREAMING
          wget -O ./community/data/rule-umum $RULE_UMUM
          wget -O rule-umum.txt $RULE_UMUM
          wget -O ./community/data/rule-ipcheck $RULE_IPCHECK
          wget -O rule-ipcheck.txt $RULE_IPCHECK
          wget -O ./community/data/videoconference $RULE_VIDCONFERENCE
          wget -O videoconference.txt $RULE_VIDCONFERENCE
          wget -O ./community/data/urltest $URLTEST
          wget -O urltest.txt $URLTEST
          wget -O ./community/data/rule-speedtest $RULE_SPEEDTEST
          wget -O rule-speedtest.txt $RULE_SPEEDTEST
          wget -O ./community/data/rule-malicious $MALICIOUS_HOST
          wget -O rule-malicious.txt $MALICIOUS_HOST
          wget -O ./community/data/bank-id $RULE_BANK_ID
          wget -O bank-id.txt $RULE_BANK_ID

      - name: Filter and save d3ward.txt
        run: |
          python <<EOF
          import requests

          # Fetch the contents of the file from the URL
          url = "https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt"
          response = requests.get(url)
          data = response.text

          # Filter lines with "0.0.0.0" and spaces and remove "0.0.0.0" text
          filtered_lines = [line.replace("0.0.0.0 ", "") for line in data.split("\n") if "0.0.0.0 " in line]

          # Save the filtered lines to a file named "d3ward.txt"
          with open("./community/data/d3ward", "w") as file:
              for line in filtered_lines:
                  file.write(line + "\n")
          EOF

      - name: Add data for `meta`
        env:
          SED: sed '/^\s*#/d' | sed 's/^PROCESS-NAME,//' | sed 's/DOMAIN,/full:/g' | sed 's/DOMAIN-SUFFIX,//g' | sed 's/DOMAIN-KEYWORD,/keyword:/g' | sed '/^\s*IP-CIDR/d'
        run: |
          curl -sSL https://raw.githubusercontent.com/xishang0128/rules/main/biliintl.list > ./community/data/biliintl
          curl -sSL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list | ${{ env.SED }} > ./community/data/onedrive
          curl -sSL https://raw.githubusercontent.com/xishang0128/rules/main/sharepoint.list > ./community/data/sharepoint
          curl -sSL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list | ${{ env.SED }} > ./community/data/tracker
          curl -sSL https://gitea.com/XIU2/TrackersListCollection/raw/branch/master/all.txt | grep -i "\.[A-Z]" | grep -v tracker | sed 's/^.*\/\///g' | sed 's/:.*\/.*//g' >> ./community/data/tracker
          curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.list | ${{ env.SED }} > ./community/data/httpdns

      - name: Build geosite.dat file
        run: |
          cd custom || exit 1
          go run ./ --datapath=../community/data

      - name: Get geoip.dat relative files
        run: |
          wget https://github.com/Loyalsoldier/geoip/raw/release/geoip.dat

      - name: Build db and metadb file
        env:
          NO_SKIP: true
        run: |
          go install -trimpath -ldflags="-s -w -buildid=" github.com/metacubex/geo/cmd/geo@master
          geo convert site -i v2ray -o sing -f geosite.db ./custom/publish/geosite.dat
          geo convert ip -i v2ray -o sing -f geoip.db ./geoip.dat
          geo convert ip -i v2ray -o meta -f geoip.metadb ./geoip.dat

      - name: Convert geo to sing-rule-set
        env:
          NO_SKIP: true
        run: |
          mkdir -p ./sing-rule/geo
          cp ./geoip.dat ./geosite.db ./resouces/convert.sh ./sing-rule/geo/ 
          cd ./sing-rule/geo
          wget https://github.com/SagerNet/sing-box/releases/download/v1.8.0-alpha.1/sing-box-1.8.0-alpha.1-linux-amd64.tar.gz -O sing-box.tar.gz && tar zxvf sing-box.tar.gz && mv sing-box-1.8.0-alpha.1-linux-amd64/sing-box ./ && rm -r sing-box-1.8.0-alpha.1-linux-amd64
          wget https://github.com/IrineSistiana/mosdns/releases/download/v4.5.3/mosdns-linux-amd64.zip -O mosdns.zip && unzip mosdns.zip
          chmod 755 mosdns sing-box convert.sh && ./convert.sh
          rm mosdns* sing-box* convert.sh geoip.dat geosite.db LICENSE README.md config.yaml

      - name: Convert geo to meta-rule-set
        env:
          NO_SKIP: true
        run: |
          mkdir -p ./meta-rule/geo
          cp ./geoip.dat ./custom/publish/geosite.dat ./resouces/convert-clash.sh ./meta-rule/geo/ 
          cd ./meta-rule/geo
          wget https://github.com/IrineSistiana/mosdns/releases/download/v4.5.3/mosdns-linux-amd64.zip -O mosdns.zip && unzip mosdns.zip
          chmod 755 mosdns convert-clash.sh && ./convert-clash.sh
          rm mosdns* convert-clash.sh geoip.dat geosite.dat LICENSE README.md config.yaml

      - name: Convert bm7-rule-set to sing-rule-set
        env:
          NO_SKIP: true
        run: |
          mkdir -p ./sing-rule/bm7
          cp ./resouces/bm7.sh ./sing-rule/bm7/
          cd ./sing-rule/bm7
          wget https://github.com/SagerNet/sing-box/releases/download/v1.8.0-alpha.1/sing-box-1.8.0-alpha.1-linux-amd64.tar.gz -O sing-box.tar.gz && tar zxvf sing-box.tar.gz && mv sing-box-1.8.0-alpha.1-linux-amd64/sing-box ./ && rm -r sing-box-1.8.0-alpha.1-linux-amd64
          ls
          chmod 755 bm7.sh && ./bm7.sh
          rm -r bm7.sh sing-box* rule

      - name: Move and zip files
        run: |
          mkdir -p ./publish/
          wget https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb -O ./publish/country.mmdb
          install -Dp ./geoip.dat ./publish/
          install -Dp ./custom/publish/geosite.dat ./publish/
          install -Dp ./geosite.db ./publish/
          install -Dp ./geoip.db ./publish/
          install -Dp ./geoip.metadb ./publish/
          cd ./publish || exit 1
          sha256sum geoip.dat > geoip.dat.sha256sum
          sha256sum geosite.dat > geosite.dat.sha256sum
          sha256sum geosite.db > geosite.db.sha256sum
          sha256sum geoip.db > geoip.db.sha256sum
          sha256sum geoip.metadb > geoip.metadb.sha256sum

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          deleteOnlyFromDrafts: false

      - name: Create and Upload Release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ env.BUILDTIME }}
          tag: latest
          file_glob: true
          overwrite: true
          file: ./publish/*

      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "Released on ${{ env.BUILDTIME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Git push assets to "sing-rule" branch
        run: |
            cd sing-rule || exit 1
            ls
            git init
            git config --local user.name "github-actions[bot]"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git checkout -b sing
            git add .
            git commit -m "Released on ${{ env.BUILDTIME }}"
            git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push -f -u origin sing

      - name: Git push assets to "meta-rule" branch
        run: |
            cd meta-rule || exit 1
            ls
            git init
            git config --local user.name "github-actions[bot]"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git checkout -b meta
            git add .
            git commit -m "Released on ${{ env.BUILDTIME }}"
            git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push -f -u origin meta


      - name: Purge jsdelivr CDN
        run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
